const CREATED = "CREATED";
const RECIEVED = "RECEIVED";
const IN_TRANSIT = "IN_TRANSIT";
const COMPLETED = "COMPLETED";
const CANCELLED = "CANCELLED";

const statusValues = [CREATED,RECIEVED,IN_TRANSIT,COMPLETED,CANCELLED];

export {CREATED,RECIEVED,IN_TRANSIT,COMPLETED,CANCELLED, statusValues};

//export default [CREATED,RECIEVED,IN_TRANSIT,COMPLETED,CANCELLED];
